version: "3.8"

services:
  bedrock:
    image: itzg/minecraft-bedrock-server:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 4G
      restart_policy:
        condition: on-failure
    environment:
      EULA: "TRUE"
      GAMEMODE: "survival"
      DIFFICULTY: "normal"
      SERVER_NAME: "BedrockServer"
      MAX_PLAYERS: 20
    ports:
      - "19132:19132/udp"
    volumes:
      - /home/patrick/minecraft-bedrock/data:/data

volumes:
  bedrock_data: