---
- name: Install and keep Docker up-to-date on Ubuntu (Raspberry Pi compatible)
  hosts: all
  become: true

  vars:
    docker_apt_repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3
        state: present
        update_cache: yes

    - name: Create keyrings directory for Docker
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker apt repository
      apt_repository:
        repo: "{{ docker_apt_repo }}"
        filename: docker
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker engine and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure unattended-upgrades is installed
      apt:
        name: unattended-upgrades
        state: present

    - name: Enable unattended-upgrades service
      systemd:
        name: unattended-upgrades
        enabled: yes
        state: started
